In [65]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [5]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
y_train.shape

(4457,)

In [11]:
y_test.shape

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [13]:
X_train[:4]

3255               I can make lasagna for you... vodka...
1421            No. She's currently in scotland for that.
2846           Will be out of class in a few hours. Sorry
3104    U so lousy, run already come back then half de...
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [15]:
y_train[:4]

3255    0
1421    0
2846    0
3104    0
Name: spam, dtype: int64

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

v=CountVectorizer()

X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7834 sparse matrix of type '<class 'numpy.int64'>'
	with 59373 stored elements in Compressed Sparse Row format>

In [19]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
X_train_cv.shape

(4457, 7834)

### There are 7834 different words in whole mails

In [22]:
v.get_feature_names_out()[1000:1030]

array(['annoying', 'anonymous', 'anot', 'another', 'ans', 'ansr',
       'answer', 'answered', 'answerin', 'answering', 'answers', 'answr',
       'antelope', 'anthony', 'anti', 'antibiotic', 'any', 'anybody',
       'anyhow', 'anymore', 'anyone', 'anyones', 'anyplaces', 'anythiing',
       'anythin', 'anything', 'anytime', 'anyway', 'anyways', 'anywhere'],
      dtype=object)

In [23]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [25]:
v.vocabulary_

{'can': 1660,
 'make': 4382,
 'lasagna': 4074,
 'for': 2986,
 'you': 7796,
 'vodka': 7410,
 'no': 4860,
 'she': 6156,
 'currently': 2161,
 'in': 3697,
 'scotland': 6030,
 'that': 6901,
 'will': 7614,
 'be': 1298,
 'out': 5073,
 'of': 4955,
 'class': 1863,
 'few': 2871,
 'hours': 3573,
 'sorry': 6421,
 'so': 6371,
 'lousy': 4278,
 'run': 5931,
 'already': 946,
 'come': 1940,
 'back': 1222,
 'then': 6916,
 'half': 3361,
 'dead': 2231,
 'hee': 3448,
 'headin': 3429,
 'towards': 7086,
 'busetop': 1602,
 'still': 6575,
 'chance': 1752,
 'there': 6921,
 'if': 3658,
 'search': 6046,
 'hard': 3393,
 'get': 3169,
 'it': 3808,
 'let': 4137,
 'have': 3416,
 'try': 7144,
 'huh': 3603,
 'early': 2550,
 'having': 3421,
 'dinner': 2372,
 'outside': 5080,
 'izzit': 3825,
 'here': 3471,
 'is': 3797,
 'your': 7800,
 'discount': 2393,
 'code': 1914,
 'rp176781': 5908,
 'to': 7015,
 'stop': 6586,
 'further': 3103,
 'messages': 4519,
 'reply': 5788,
 'www': 7730,
 'regalportfolio': 5734,
 'co': 1904,
 'uk'

In [66]:
v.get_feature_names_out()[1660]

'can'

In [27]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
np.where(X_train_np[0]!=0)

(array([1660, 2986, 4074, 4382, 7410, 7796], dtype=int64),)

In [30]:
X_train[:1][3255]

'I can make lasagna for you... vodka...'

In [33]:
X_train_np[0][4074]

1

In [34]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [35]:
X_test_cv=v.transform(X_test)

In [36]:
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       982
           1       0.94      0.89      0.92       133

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [37]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [38]:
from sklearn.pipeline import Pipeline

clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [39]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [41]:
y_pred=clf.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       982
           1       0.94      0.89      0.92       133

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115



### By The help of GaussianNB

In [44]:
from sklearn.naive_bayes import GaussianNB

model=GaussianNB()
model.fit(X_train_np,y_train)

GaussianNB()

In [47]:
X_test_np=X_test_cv.toarray()
y_pred=model.predict(X_test_np)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.90      0.94       982
           1       0.55      0.93      0.69       133

    accuracy                           0.90      1115
   macro avg       0.77      0.91      0.81      1115
weighted avg       0.94      0.90      0.91      1115



## Bag of words: Exercises
1. In this Exercise, you are going to classify whether a given movie review is positive or negative.
2. you are going to use Bag of words for pre-processing the text and apply different classification algorithms.
3. Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

In [48]:
#Import necessary libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

#### About Data: IMDB Dataset
Credits: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?resource=download

1. This data consists of two columns. - review - sentiment
2. Reviews are the statements given by users after watching the movie.
3. sentiment feature tells whether the given review is positive or negative.

In [57]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
df=pd.read_csv("IMDB Dataset.csv")


#2. print the shape of the data
print(df.shape)

#3. print top 5 datapoints
print(df.head())

(50000, 2)
                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive


In [58]:
#creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative
df['Category']=df['sentiment'].apply(lambda x:1 if x=='positive' else 0)
df.head()

review sentiment  Category
0  One of the other reviewers has mentioned that ...  positive         1
1  A wonderful little production. <br /><br />The...  positive         1
2  I thought this was a wonderful way to spend ti...  positive         1
3  Basically there's a family where a little boy ...  negative         0
4  Petter Mattei's "Love in the Time of Money" is...  positive         1

In [61]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.
df.Category.value_counts()

1    25000
0    25000
Name: Category, dtype: int64

Yes,The Target labels are balanced

In [63]:
#Do the 'train-test' splitting with test size of 20%

X_train,X_test,y_train,y_test=train_test_split(df.review,df.Category,test_size=0.2)

#### Exercise-1

using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.
Note:

1. use CountVectorizer for pre-processing the text.

2. use Random Forest as the classifier with estimators as 50 and criterion as entropy.

3. print the classification report.

References:

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [67]:
#1. create a pipeline object

clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('Random forest',RandomForestClassifier(n_estimators=50,  criterion='entropy'))
])


#2. fit with X_train and y_train

clf.fit(X_train,y_train)

#3. get the predictions for X_test and store it in y_pred

y_pred=clf.predict(X_test)

#4. print the classfication report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84      5073
           1       0.83      0.83      0.83      4927

    accuracy                           0.83     10000
   macro avg       0.83      0.83      0.83     10000
weighted avg       0.83      0.83      0.83     10000



#### Exercise-2

using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..
Note:

1. use CountVectorizer for pre-processing the text.
2. use KNN as the classifier with n_neighbors of 10 and metric as 'euclidean'.
3. print the classification report.
References:

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [68]:
#1. create a pipeline object

clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('KNN',KNeighborsClassifier(n_neighbors=10,  metric='euclidean'))
])


#2. fit with X_train and y_train

clf.fit(X_train,y_train)

#3. get the predictions for X_test and store it in y_pred

y_pred=clf.predict(X_test)

#4. print the classfication report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.66      0.66      0.66      5073
           1       0.65      0.65      0.65      4927

    accuracy                           0.65     10000
   macro avg       0.65      0.65      0.65     10000
weighted avg       0.65      0.65      0.65     10000



#### Exercise-3

using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..
Note:

1. use CountVectorizer for pre-processing the text.
2. use Multinomial Naive Bayes as the classifier.
3. print the classification report.
References:

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html

In [69]:
#1. create a pipeline object

clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('naive_bayes',MultinomialNB())
])


#2. fit with X_train and y_train

clf.fit(X_train,y_train)

#3. get the predictions for X_test and store it in y_pred

y_pred=clf.predict(X_test)

#4. print the classfication report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.86      5073
           1       0.87      0.82      0.84      4927

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000



### Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?

### Ans
- Yes ,In KNN we select our nearest 10 points by the help of euclidean distance but it is not related to the nearest points it dependes on some type of wors for example Won $10 Million,You are Lucky Winner,90% discount etc

- In this process, we convert text into a very high dimensional numeric vector using the technique of Bag of words.
Model like K-Nearest Neighbours(KNN) doesn't work well with high dimensional data because with large number of dimensions, it becomes difficult for the algorithm to calculate distance in each dimension. In higher dimensional space, the cost to calculate distance becomes expensive and hence impacts the performance of model.